services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spotlightdb'
      - 'POSTGRES_PASSWORD=secretspotlightdb'
      - 'POSTGRES_USER=userspotlight'
    ports:
      - '5432:5432'
    volumes:
      - './volumes/spotlight/postgres:/var/lib/postgresql/data'
